name: SmallSpark
favicon: null
layout_spectrum: 0.5790836133528501
typography_spectrum: 0.6565754027105868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#040809'
    - '#d9ccbb'
    - '#45444a'
    - '#766f65'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
