name: SmallSpark
favicon: null
layout_spectrum: 0.49545
typography_spectrum: 0.76052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252531'
    - '#817e75'
    - '#454346'
    - '#d0c3b0'
    - '#b89150'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
